$DocsPath = 'C:\Source\GEEK\Sentinel\website\docs'
$Modules = Get-ChildItem -Path $DocsPath -Directory

$Lines = @('module.exports = {', '  tutorialSidebar: [')
foreach ($M in $Modules) {
    $Label = (Get-Culture).TextInfo.ToTitleCase($M.Name.Replace('-', ' '))
    $Lines += "    {"
    $Lines += "      type: 'category',"
    $Lines += "      label: '$Label',"
    $Lines += "      items: [{"
    $Lines += "        type: 'autogenerated',"
    $Lines += "        dirName: '$($M.Name)',"
    $Lines += "      }],"
    $Lines += "    },"
}
$Lines += '  ],'
$Lines += '};'

$Lines -join "`n" | Out-File 'C:\Source\GEEK\Sentinel\website\sidebars.js' -Encoding utf8 -Force
Write-Host 'Sidebars updated'
Get-Content 'C:\Source\GEEK\Sentinel\website\sidebars.js'
