'Project_Status':
  'Version': '17.7'
  'Codenames':
    'Network': 'Source'
    'Machine': 'GEEK'
    'Volume': 'S:'
  'DriveIcon': 'the-source.ico'

'Root_Layout':
  'GitHub_Repo': 'C:\Users\mille\Documents\GitHub\sentinel-media-sync'
  'Data_Root': 'C:\Source'
  'Network_Share': '\\GEEK\Source'
  'Mapped_Drive': 'S:\'

'Settings':
  'LogPath': '_log'
  'TemplateDir': 'C:\Users\mille\Documents\GitHub\sentinel-media-sync\templates'
  'MonitorDepth': 3
  'PurgeWebsite': true
#  if prunewebsite, purgewebsite is forced to false
  'PruneWebsite': false
  'DisableJunkPurge': true
  'DryRun': false
  'GlobalOverwrite': true
  'EmailSettings':
    'Enabled': true
    'To': 'millerjohneric@gmail.com'
    'CredPath': '.secure\gmail.cred'
  'DefaultYear': 2026
  'DateFormat': '%Y/%m Month'
  'ChronoRegex': '^\d{4}/\d{2}\s\w+$'
  'EventRegex': '^([a-zA-Z0-9_\-\s]+[/\])*[a-zA-Z0-9_\-\s]+$'
  'FileTypes':
    'Exclusions':
      - '.webaxs'
      - 'trashbox'
      - '.git'
      - '$RECYCLE.BIN'
      - '_putaway'
      - 'System Volume Information'
    'Images': [ '.jpg', '.jpeg', '.png', '.heic', '.tif', '.tiff' ]
    'RAWs': [ '.nef', '.cr2', '.arw', '.dng' ]
    'Videos': [ '.mp4', '.mov', '.avi', '.mkv' ]
    'Audio': [ '.mp3', '.wav', '.flac', '.m4a' ]
    'Docs': [ '.pdf', '.docx', '.txt' ]
    'Web': [ '.md', '.html' ]
    'Sidecars': [ '.xmp', '.json', '.xml', '.yml' ]
    'Junk':
      - 'Thumbs.db'
      - 'desktop.ini'
      - '.DS_Store'
      - 'ehthumbs.db'
    'WebContent':
      - 'Images'
      - 'Docs'
      - 'Sidecars'
      - 'Web'
      - '.mp4'
      - '.yml'

'Locations':
  - 'Name': 'Source Studio Engine'
    'Path': 'C:\Source\GEEK\Sentinel\website\docs'
    'SitePath': 'C:\Source_Studio\website'
    'Role': 'Website'
    'WebSubFolder': 'docs'
    'RootType': 'web-root'
    'AutoStart': true

  - 'Name': 'Culinary Cuisine'
    'Path': 'C:\Source\GEEK\culinary-cuisine\website'
    'SitePath': 'C:\Source_Studio\website'
    'Role': 'Website'
    'WebSubFolder': 'culinary-cuisine'
    'SiteUrl': 'http://millerjohneric.asuscomm.com:3000'
    'Template': 'recipe-card'
    'RootType': 'web-culinary'
    'MonitorDepth': 99
    'SortDepth': null
    'Overwrite': true
    'PurgeOrphan': true
    'GroupSeparator': '-.-'
    'Structure':
      - 'Event'

  - 'Name': 'jems-tones'
    'Path': 'C:\Source\GEEK\Photography_Hobby\website'
    'SitePath': 'C:\Source_Studio\website'
    'Role': 'Website'
    'WebSubFolder': 'jems-tones'
    'SiteUrl': 'http://millerjohneric.asuscomm.com:3000'
    'Template': 'masonry-grid'
    'RootType': 'web-gallery'
    'MonitorDepth': 99
    'SortDepth': null
    'Overwrite': true
    'PurgeOrphan': true
    'GroupSeparator': '-.-'
    'Structure':
      - 'Event'

  - 'Name': 'millermade-handcrafted'
    'Path': 'C:\Source\GEEK\millermade-handcrafted\website'
    'SitePath': 'C:\Source_Studio\website'
    'Role': 'Website'
    'WebSubFolder': 'millermade-handcrafted'
    'SiteUrl': 'http://millerjohneric.asuscomm.com:3000'
    'Template': 'hand-crafted'
    'RootType': 'web-shop'
    'MonitorDepth': 99
    'SortDepth': null
    'Overwrite': true
    'PurgeOrphan': true
    'GroupSeparator': '-.-'
    'Structure':
      - 'Event'

# --- ARCHIVES (Destinations) ---
  - 'Name': 'timeline'
    'Path': 'C:\Source\GEEK\Photo_Archive\timeline'
    'Role': 'timeline'
    'MonitorDepth': 1
    'SortDepth': 1
    'RootType': 'Photos'
    'PurgeOrphan': false
    'Structure':
      - 'Chrono'
      -
  - 'Name': 'Photography_RAW'
    'Path': 'C:\Source\GEEK\Photography_Hobby\_RAW'
    'Role': 'RAW_Archive'
    'MonitorDepth': 1
    'SortDepth': 1
    'PurgeOrphan': false
    'RootType': 'RAW'
    'Structure':
      - 'Chrono'
      - 'Event'

  - 'Name': 'Shadow_Echoes'
    'Path': 'C:\Source\GEEK\Photo_Archive\Shadow_Echoes'
    'Role': 'InPlace_Archive'
    'MonitorDepth': 2
    'PurgeOrphan': false
    'RootType': 'Hybrid'
    'Structure':
      - 'Chrono'
      - 'Event'

  - 'Name': 'Visual_Registry'
    'Path': 'C:\Source\GEEK\Photo_Archive\Visual_Registry'
    'Role': 'InPlace_Archive'
    'MonitorDepth': 2
    'PurgeOrphan': false
    'RootType': 'Hybrid'
    'Structure':
      - 'Chrono'
      - 'Event'

  - 'Name': 'Legends'
    'Path': 'C:\Source\GEEK\Photo_Archive\Legends'
    'Role': 'InPlace_Archive'
    'MonitorDepth': 2
    'PurgeOrphan': false
    'RootType': 'Hybrid'
    'Structure':
      - 'Chrono'
      - 'Event'

# --- PASSIVE SINKS ---
  - 'Name': 'Videos'
    'Path': 'C:\Source\GEEK\Movies_and_Videos\Videos'
    'Role': 'Video_Archive'
    'MonitorDepth': 0
    'SortDepth': 1
    'PurgeOrphan': false
    'RootType': 'Videos'
    'Structure':
      - 'Chrono'

  - 'Name': 'Sonic_Discography'
    'Path': 'C:\Source\GEEK\Music\Sonic_Discography'
    'Role': 'Audio_Archive'
    'MonitorDepth': 0
    'SortDepth': 1
    'PurgeOrphan': false
    'RootType': 'Audio'
    'Structure':
      - 'Chrono'

# --- PICKUP ZONES (Loading Zones) ---
  - 'Name': 'John'
    'Path': '\\LS720DB34C\share\Sorting_Limbo\-in-box\John'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'

  - 'Name': 'Roena'
    'Path': '\\LS720DB34C\share\Sorting_Limbo\-in-box\Roena'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'

  - 'Name': 'BigAssTablet'
    'Path': '\\LS720DB34C\share\Sorting_Limbo\-in-box\BigAssTablet'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'

  - 'Name': 'Downloads'
    'Path': 'C:\Source\GEEK\Sorting_Limbo\-in-box\Downloads'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'

  - 'Name': 'CzurDoc'
    'Path': 'C:\Users\mille\Documents\CzurDoc\sources'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'

  - 'Name': 'SnippingTool'
    'Path': 'C:\Users\mille\Pictures\SnippingTool'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'

  - 'Name': 'ControlCenter4'
    'Path': 'C:\Users\mille\Pictures\ControlCenter4\Scan'
    'Role': 'Pickup'
    'MonitorDepth': 99
    'SortDepth': 0
    'PurgeOrphan': false
    'Scope': 'Global'
    'Structure':
      - 'Chrono'
