# ==============================================================================
# Sentinel Web Gen v20.7 [REGISTRY & UI FIX]
# ==============================================================================
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$globalStopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# 1. Setup & Dot-Sourcing
$CorePath = Join-Path $PSScriptRoot 'Sentinel-Core.ps1'
if (Test-Path $CorePath) { . $CorePath } else { Write-Error 'Core missing!'; exit }

Import-Module powershell-yaml
$ConfigFilePath = Join-Path $PSScriptRoot 'config2.0.yml'
$YamlData = Get-Content $ConfigFilePath -Raw | ConvertFrom-Yaml
$WebLocations = $YamlData.Locations
$GlobalSettings = $YamlData.Settings

# --- ROBUST PATH FIX ---
$TemplateDir = $GlobalSettings.TemplateDir
$MaxDepth = if ($GlobalSettings.MonitorDepth) { $GlobalSettings.MonitorDepth } else { 3 }
$GlobalStats = @{ Created = 0; Skipped = 0; Errors = 0 }

# --- PHASE 1: CONFIGURATION & REGISTRY GENERATION ---
Write-Host "`nPHASE 1: Synchronizing Site Templates & Registry..." -ForegroundColor White

$RelevantLocs = $WebLocations | Where-Object { $_.Role -eq 'Hybrid_Archive' }

Write-Host "`nPHASE 0: Active Web Archive Targets" -ForegroundColor White
Write-Host "---------------------------------------" -ForegroundColor Gray
foreach ($loc in $RelevantLocs) {
    $SubDir = if ($loc.WebSubFolder) { $loc.WebSubFolder } else { $loc.Name -replace '\s+', '-' }
    Write-Host "  $($Global:Icons.Arrow) Archive: $($loc.Name)" -ForegroundColor Cyan
    Write-Host "    Source:  $($loc.Path)" -ForegroundColor Gray
    Write-Host "    Target:  $SubDir" -ForegroundColor Gray
}
Write-Host "---------------------------------------" -ForegroundColor Gray

# --- PHASE 1: TEMPLATE & REGISTRY SYNC ---
Write-Host "`nPHASE 1: Synchronizing Site Templates & Nav Registry..." -ForegroundColor White

$NavRegistry = @()
$SidebarContent = "  'defaultSidebar': [{'type': 'autogenerated', 'dirName': '.'}],`n"
$PluginConfig = "    ['@docusaurus/plugin-content-docs', { 'id': 'docs', 'path': 'docs', 'routeBasePath': 'docs', 'sidebarPath': require.resolve('./sidebars.js') }],`n"

foreach ($loc in $RelevantLocs) {
    $FolderID = if ($loc.WebSubFolder) { $loc.WebSubFolder } else { $loc.Name -replace '\s+', '-' }

    # Add to Navigation Registry for React Home Page
    $NavRegistry += [PSCustomObject]@{
        'title' = $loc.Name
        'description' = "Unified $($loc.RootType) Archive"
        'link' = "/$FolderID"
    }

    $SidebarContent += "  '$FolderID': [{'type': 'autogenerated', 'dirName': '.'}],`n"
    $PluginConfig += "    ['@docusaurus/plugin-content-docs', { 'id': '$FolderID', 'path': '$FolderID', 'routeBasePath': '$FolderID', 'sidebarPath': require.resolve('./sidebars.js') }],`n"
}

# --- CRITICAL: Save and Copy Registry immediately ---
$RegistryPath = Join-Path $TemplateDir 'nav-registry.json'
$NavRegistry | ConvertTo-Json | Set-Content -Path $RegistryPath -Force

# Push to Live Site to fix "Module Not Found"
$SitePath = ($WebLocations | Where-Object { $_.SitePath -like '*website*' } | Select-Object -First 1).SitePath
if (Test-Path $SitePath) {
    $DestPages = Join-Path $SitePath "src\pages"
    if (-not (Test-Path $DestPages)) { New-Item $DestPages -ItemType Directory -Force | Out-Null }
    Copy-Item $RegistryPath -Destination (Join-Path $DestPages "nav-registry.json") -Force
    Write-Host "  $($Global:Icons.Check) Registry deployed to $DestPages" -ForegroundColor Green
}

# Write Sidebars and Config
$SidebarPath = Join-Path $TemplateDir 'sidebars.js'
Set-Content -Path $SidebarPath -Value "module.exports = {`n$SidebarContent};" -Force
$ConfigTemplate = @"
module.exports = {
  'title': 'Source Studio',
  'url': 'http://localhost',
  'baseUrl': '/',
  'favicon': 'favicon.ico',
  'themeConfig': {
    'navbar': {
      'title': 'Source Studio',
      'logo': { 'alt': 'Logo', 'src': 'img/logo.svg' }
    }
  },
  'markdown': {
    'format': 'mdx',
    'mermaid': true,
    'preprocessor': ({ filePath, content }) => { return content; },
    'remarkRehypeOptions': {
      'handlers': { 'directive': null }
    }
  },
  'presets': [[
    'classic',
    {
      'docs': false,
      'blog': false,
      'theme': { 'customCss': require.resolve('./src/css/custom.css') }
    }
  ]],
  'plugins': [
$PluginConfig  ],
};
"@
Set-Content -Path (Join-Path $TemplateDir 'docusaurus.config.js') -Value $ConfigTemplate -Force

# --- PHASE 2: SITE INITIALIZATION ---
Write-Host "`nPHASE 2: Spawning Unified Website..." -ForegroundColor White
$MasterSite = $WebLocations | Where-Object { $_.AutoStart -eq $true } | Select-Object -First 1

if ($MasterSite) {
    # The function now handles the Wipe check internally via YAML
    $IsReady = Initialize-SentinelWebRoot -RootPath $MasterSite.SitePath

    if ($IsReady) {
        $OnlineStatus = Start-SentinelWebsite -Path $MasterSite.SitePath -Locations $WebLocations
    }
}

# --- PRE-PHASE 3: EXTENSION FLATTENING ---
$AllowedExts = Get-SentinelWebExtensions -FileTypeData $YamlData.FileTypes
$TransformExts = $YamlData.FileTypes.Web | ForEach-Object { $_.ToLower().TrimStart('.') }
$AssetExts = $AllowedExts | Where-Object { $_ -notin $TransformExts }

# Calculate Total for Progress Bar
$TotalFilesAcrossAll = 0
foreach ($l in $RelevantLocs) {
    $TotalFilesAcrossAll += (Get-ChildItem -Path $l.Path -File -Recurse | Where-Object { $_.Extension.ToLower().TrimStart('.') -in $AllowedExts }).Count
}
$CurrentGlobalCount = 0

# --- PHASE 3: CONTENT GENERATION ---
Write-Host "`nPHASE 3: Building MDX via Grouping..." -ForegroundColor White

foreach ($loc in $RelevantLocs) {
    $FolderID = if ($loc.WebSubFolder) { $loc.WebSubFolder } else { $loc.Name -replace '\s+', '-' }
    $TargetDir = Join-Path $MasterSite.SitePath $FolderID # Path where .md and images go

    # Gather and Group
    $AllFiles = Get-ChildItem -Path $loc.Path -File -Recurse | Where-Object { $_.Extension.ToLower().TrimStart('.') -in $AllowedExts }

    # Group by filename stripping the -.- suffix
    $FileGroups = $AllFiles | Group-Object { $_.BaseName -replace '-.-.*$', '' }

    foreach ($group in $FileGroups) {
        $CurrentGlobalCount += $group.Count

        Write-Progress -Activity "Building Site" -Status "Processing: $($loc.Name)" -PercentComplete (($CurrentGlobalCount/$TotalFilesAcrossAll)*100)
        Write-SentinelOdometer -Tag 'BUILD' -Source $loc.Name -Path $group.Name -Current $CurrentGlobalCount -Total $TotalFilesAcrossAll

        # Execute Build with Asset Support
        [int]$NewFiles = Build-WebPageFromTemplate -SourceFiles $group.Group `
                                                   -TargetFolder $TargetDir `
                                                   -TemplateType $loc.Template `
                                                   -Overwrite $loc.Overwrite `
                                                   -AssetExts $AssetExts
        $GlobalStats.Created += $NewFiles
    }
}
Write-Progress -Activity "Building Site" -Completed

# --- PHASE 4: LAUNCH SERVER ---
if ($MasterSite -and $IsReady) {
    Write-Host "`nPHASE 4: Launching Development Server..." -ForegroundColor White
    $OnlineStatus = Start-SentinelWebsite -Path $MasterSite.SitePath -Locations $WebLocations
}

$globalStopwatch.Stop()
$Duration = $globalStopwatch.Elapsed.ToString("mm\:ss")

Write-Host "`n`nSENTINEL SYNC COMPLETE" -ForegroundColor Green
Write-Host "---------------------------------------" -ForegroundColor Gray
$StatusColor = if ($StatusText -eq 'ONLINE') { 'Green' } else { 'Yellow' }
Write-Host "  Site Status:   $StatusText" -ForegroundColor $StatusColor
Write-Host "  Duration:      $Duration"
Write-Host "  New Created:   $($GlobalStats.Created)" -ForegroundColor Cyan
Write-Host "  Preserved:     $($GlobalStats.Skipped)" -ForegroundColor Gray
Write-Host "  Errors:        $($GlobalStats.Errors)" -ForegroundColor Red
Write-Host "---------------------------------------`n" -ForegroundColor Gray

# --- COMPLETION NOTIFICATION ---
# Plays a system notification sound (Beep) to alert you that the build is done
[System.Media.SystemSounds]::Asterisk.Play()