$ModuleRoot = Split-Path $PSScriptRoot -Parent
$ConfigPath = Join-Path $ModuleRoot "Sentinel-Config.yml"

if (-not (Test-Path $ConfigPath)) {
    Write-Warning "Configuration file not found at path: $ConfigPath"
    return
}

$YamlData = Get-Content $ConfigPath -Raw
$SiteName = if ($YamlData.Settings.SiteName) { $YamlData.Settings.SiteName } else { "Source Studio" }
$Modules  = $YamlData.Locations | Where-Object { $_.Role -eq 'Website' -and $_.RootType -ne 'web-root' }

$Cards = ""
foreach ($M in $Modules) {
    $Name = $M.Name
    $Slug = $Name.ToLower().Replace(' ', '-')
    $Type = ($M.RootType -replace 'web-', '')
    $Type = (Get-Culture).TextInfo.ToTitleCase($Type)
    $Path = $M.Path
    $Cards += "`n## [$Name](/docs/$Slug)`n`n**Type:** $Type  `n**Source:** ``$Path```n"
}

$Content = "---`nid: index`ntitle: '$SiteName'`nsidebar_label: 'Overview'`nsidebar_position: 1`nslug: /`n---`n`n# $SiteName`n`nWelcome to the Sentinel-generated knowledge base. Below are the active content modules synced into this site.`n`n---`n$Cards`n---`n`n*Generated by Sentinel Sync*`n"

foreach ($Path in @("C:\Source\GEEK\Sentinel\website\docs\index.md", "C:\Source_Studio\website\docs\index.md")) {
    $Dir = Split-Path $Path
    if (Test-Path $Dir) {
        [System.IO.File]::WriteAllText($Path, $Content)
        Write-Host "Written: $Path"
    }
}
