function Write-SentinelSidebars {
    param([string]$SitePath)

    $DocsPath = Join-Path $SitePath "docs"
    if (!(Test-Path $DocsPath)) { return }

    Write-Host "  $($Global:Icons.Check) Dynamically generating sidebars.js..." -ForegroundColor Cyan

    $Modules = Get-ChildItem -Path $DocsPath -Directory

    $SidebarLines = @()
    $SidebarLines += "module.exports = {"
    
    foreach ($M in $Modules) {
        $ModuleName = $M.Name
        $SidebarId = $ModuleName + "Sidebar"
        $SidebarLines += "  ${SidebarId}: ["
        $SidebarLines += "    {"
        $SidebarLines += "      type: 'autogenerated',"
        $SidebarLines += "      dirName: '.',"
        $SidebarLines += "    },"
        $SidebarLines += "  ],"
    }
    
    $SidebarLines += "  tutorialSidebar: ["
    $SidebarLines += "    {"
    $SidebarLines += "      type: 'autogenerated',"
    $SidebarLines += "      dirName: '.',"
    $SidebarLines += "    },"
    $SidebarLines += "  ],"

    $SidebarLines += "};"

    $FinalJS = $SidebarLines -join "`n"
    $SidebarFile = Join-Path $SitePath "sidebars.js"
    [System.IO.File]::WriteAllText($SidebarFile, $FinalJS, [System.Text.UTF8Encoding]::new($false))
}
