# ==============================================================================
# Sentinel Web Gen v20.14 [ADJACENT PLUGIN ARCHITECTURE]
# ==============================================================================
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$globalStopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# 1. Setup & Dot-Sourcing
$BaseDir = $PSScriptRoot
Set-Location $BaseDir
$CorePath = Join-Path $BaseDir 'Sentinel-Core.ps1'
if (Test-Path $CorePath) { . $CorePath } else { Write-Error 'Core missing!'; exit }

Import-Module powershell-yaml -ErrorAction SilentlyContinue
$ConfigFilePath = Join-Path $BaseDir 'Sentinel-Config.yml'
$YamlData = Get-Content $ConfigFilePath -Raw | ConvertFrom-Yaml

$WebLocations = $YamlData.Locations
$GlobalSettings = $YamlData.Settings
$TemplateDir = $GlobalSettings.TemplateDir

# --- IDENTIFY TARGETS ---
$MasterSite = $WebLocations | Where-Object { $_.Role -eq 'Website' -and $_.SitePath } | Select-Object -First 1
$TargetWebsitePath = $MasterSite.SitePath
$ContentLocs = $WebLocations | Where-Object { $_.Role -eq 'Website' -and $_.WebSubFolder -ne 'docs' }

# --- PHASE 0: PREP ---
Write-Host "PHASE 0: Stopping existing Node services..." -ForegroundColor Yellow
Get-Process node -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 2

# --- PHASE 1: INITIALIZE ENGINE ---
Write-Host "PHASE 1: Ensuring Engine Integrity..." -ForegroundColor Cyan
Initialize-SentinelWebRoot -RootPath $TargetWebsitePath

# --- PHASE 2: DYNAMIC CONFIG & SIDEBARS ---
Write-Host "PHASE 2: Generating Config & Sidebars..." -ForegroundColor White
$SidebarContent = "  'defaultSidebar': [{'type': 'autogenerated', 'dirName': '.'}],`n"
$PluginConfig = "    ['@docusaurus/plugin-content-docs', { 'id': 'docs', 'path': 'docs', 'routeBasePath': 'docs' }],`n"

foreach ($loc in $ContentLocs) {
    $FolderID = $loc.WebSubFolder
    $SidebarContent += "  '$FolderID': [{'type': 'autogenerated', 'dirName': '.'}],`n"
    $PluginConfig += "    ['@docusaurus/plugin-content-docs', { 'id': '$FolderID', 'path': '$FolderID', 'routeBasePath': '$FolderID' }],`n"

    $SeedPath = Join-Path $TargetWebsitePath $FolderID
    if (!(Test-Path $SeedPath)) { New-Item -Path $SeedPath -ItemType Directory -Force | Out-Null }
    $PlaceholderFile = Join-Path $SeedPath "index.md"
    if (!(Test-Path $PlaceholderFile)) {
        $DefaultContent = "---`ntitle: $($loc.Name)`n---`n`n# $($loc.Name)`n`nWaiting for content synchronization..."
        Set-Content -Path $PlaceholderFile -Value $DefaultContent -Encoding UTF8
    }
}

Set-Content -Path (Join-Path $TargetWebsitePath 'sidebars.js') -Value "module.exports = {`n$SidebarContent};" -Force

$ConfigTemplate = @"
module.exports = {
  'title': 'Source Studio',
  'url': 'http://localhost',
  'baseUrl': '/',
  'favicon': 'img/favicon.ico',
  'themeConfig': { 'navbar': { 'title': 'Source Studio', 'logo': { 'alt': 'Logo', 'src': 'img/logo.svg' } } },
  'markdown': { 'format': 'mdx' },
  'themes': ['@docusaurus/theme-mermaid'],
  'presets': [['classic', { 'docs': { 'sidebarPath': require.resolve('./sidebars.js') }, 'blog': false, 'theme': { 'customCss': require.resolve('./src/css/custom.css') } }]],
  'plugins': [
$PluginConfig  ],
};
"@
Set-Content -Path (Join-Path $TargetWebsitePath 'docusaurus.config.js') -Value $ConfigTemplate -Force

# --- PHASE 3: EXECUTE BUILD (STRUCTURE PRESERVATION) ---
foreach ($loc in $ContentLocs) {
    Write-Host "`nProcessing Location: $($loc.Name)" -ForegroundColor Cyan

    $SourcePath = $loc.Path
    $PluginSubFolder = if ($loc.WebSubFolder) { $loc.WebSubFolder } else { 'docs' }
    $PluginRootPath = Join-Path $TargetWebsitePath $PluginSubFolder

    $AllFiles = Get-ChildItem -Path $SourcePath -Recurse -File | Where-Object {
        $_.Name -notmatch 'index.md|_category_.yml'
    }

    $GroupSeparator = if ($loc.GroupSeparator) { $loc.GroupSeparator } else { '-.-' }
    $FileGroups = $AllFiles | Group-Object {
        $BN = $_.BaseName
        if ($BN -match [regex]::Escape($GroupSeparator)) {
            $BN.Substring(0, $BN.LastIndexOf($GroupSeparator))
        } else { $BN }
    }

    foreach ($group in $FileGroups) {
        $FullDir = $group.Group[0].DirectoryName
        $RelativeDir = $FullDir.Replace($SourcePath, "").TrimStart('\')

        $TargetDir = if ([string]::IsNullOrWhiteSpace($RelativeDir)) {
            $PluginRootPath
        } else {
            Join-Path $PluginRootPath $RelativeDir
        }

        if (!(Test-Path $TargetDir)) { New-Item -Path $TargetDir -ItemType Directory -Force | Out-Null }

        $ExtList = @()
        foreach ($Item in $YamlData.FileTypes.WebContent) {
            if ($YamlData.FileTypes.$Item) {
                $ExtList += $YamlData.FileTypes.$Item
            } else {
                $ExtList += $Item
            }
        }

        # Inside Sentinel Web Gen.ps1 -> PHASE 3
        Build-WebPageFromTemplate `
            -SourceFiles $group.Group `
            -TargetFolder $TargetDir `
            -AssetExts $ExtList `
            -Overwrite $true `
            -FolderName $loc.Name `
            -RootType $loc.RootType # Ensure this line exists!
    }
}

# --- PHASE 4: GLOBAL ASSETS ---
if (Test-Path $TemplateDir) {
    Copy-Item "$TemplateDir\custom.css" (Join-Path $TargetWebsitePath "src/css/custom.css") -Force -ErrorAction SilentlyContinue
    Get-ChildItem $TemplateDir -Include *.ico, *.svg, *.png | Copy-Item -Destination (Join-Path $TargetWebsitePath "static/img") -Force
}

# --- PHASE 5: LAUNCH ---
Write-Host "PHASE 5: Launching Server..." -ForegroundColor Cyan
Start-SentinelWebsite -Path $TargetWebsitePath -Locations $WebLocations

$globalStopwatch.Stop()
Write-Host "---------------------------------------" -ForegroundColor White
Write-Host " OK: Adjacent Sync Complete ($($globalStopwatch.Elapsed.ToString('mm\:ss')))." -ForegroundColor Cyan