# ==============================================================================
# Sentinel Web Gen v20.15 [DYNAMIC PLUGIN INJECTION]
# ==============================================================================
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$globalStopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# -1. Setup & Dot-Sourcing
$BaseDir = $PSScriptRoot
Set-Location $BaseDir
$CorePath = Join-Path $BaseDir 'Sentinel-Core.ps1'
if (Test-Path $CorePath) { . $CorePath } else { Write-Error 'Core missing!'; exit }

Import-Module powershell-yaml -ErrorAction SilentlyContinue
$ConfigFilePath = Join-Path $BaseDir 'Sentinel-Config.yml'
$YamlData = Get-Content $ConfigFilePath -Raw | ConvertFrom-Yaml

$WebLocations = $YamlData.Locations
$GlobalSettings = $YamlData.Settings
$TemplateDir = $GlobalSettings.TemplateDir

# --- IDENTIFY TARGETS ---
$MasterSite = $WebLocations | Where-Object { $_.Role -eq 'Website' -and $_.SitePath } | Select-Object -First 1
$TargetWebsitePath = $MasterSite.SitePath
$ContentLocs = $WebLocations | Where-Object { $_.Role -eq 'Website' -and $_.WebSubFolder -ne 'docs' }

# --- PHASE 0: PREP ---
Write-Host "PHASE 0: Stopping existing Node services..." -ForegroundColor Yellow
Get-Process node -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 2

# --- PHASE 1: INITIALIZE ENGINE ---
Write-Host "PHASE 1: Ensuring Engine Integrity..." -ForegroundColor Cyan
Initialize-SentinelWebRoot -RootPath $TargetWebsitePath

# --- PHASE 2: DYNAMIC CONFIG & SIDEBARS ---
Write-Host "PHASE 2: Generating Config & Sidebars..." -ForegroundColor White
$SidebarContent = "  'defaultSidebar': [{'type': 'autogenerated', 'dirName': '.'}],`n"
$PluginConfig = "    ['@docusaurus/plugin-content-docs', { 'id': 'docs', 'path': 'docs', 'routeBasePath': 'docs' }],`n"

foreach ($loc in $ContentLocs) {
    $FolderID = $loc.WebSubFolder
    $SidebarContent += "  '$FolderID': [{'type': 'autogenerated', 'dirName': '.'}],`n"
    $PluginConfig += "    ['@docusaurus/plugin-content-docs', { 'id': '$FolderID', 'path': '$FolderID', 'routeBasePath': '$FolderID' }],`n"

    $SeedPath = Join-Path $TargetWebsitePath $FolderID
    if (!(Test-Path $SeedPath)) { New-Item -Path $SeedPath -ItemType Directory -Force | Out-Null }
    $PlaceholderFile = Join-Path $SeedPath "index.md"
    if (!(Test-Path $PlaceholderFile)) {
        $DefaultContent = "---`ntitle: $($loc.Name)`n---`n`n# $($loc.Name)`n`nWaiting for content synchronization..."
        Set-Content -Path $PlaceholderFile -Value $DefaultContent -Encoding UTF8
    }
}

Set-Content -Path (Join-Path $TargetWebsitePath 'sidebars.js') -Value "module.exports = {`n$SidebarContent};" -Force

$ConfigTemplate = @"
module.exports = {
  'title': 'Source Studio',
  'url': 'http://localhost',
  'baseUrl': '/',
  'favicon': 'img/favicon.ico',
  'themeConfig': { 'navbar': { 'title': 'Source Studio', 'logo': { 'alt': 'Logo', 'src': 'img/logo.svg' } } },
  'markdown': { 'format': 'mdx' },
  'themes': ['@docusaurus/theme-mermaid'],
  'presets': [['classic', { 'docs': { 'sidebarPath': require.resolve('./sidebars.js') }, 'blog': false, 'theme': { 'customCss': require.resolve('./src/css/custom.css') } }]],
  'plugins': [
$PluginConfig  ],
};
"@
Set-Content -Path (Join-Path $TargetWebsitePath 'docusaurus.config.js') -Value $ConfigTemplate -Force

# --- PHASE 3: EXECUTE BUILD (STRUCTURE PRESERVATION) ---
foreach ($loc in $ContentLocs) {
    Write-Host "`nProcessing Location: $($loc.Name)" -ForegroundColor Cyan

# --- PHASE 1: CONFIG GENERATION ---
Write-Host "PHASE 1: Dynamically configuring Docusaurus Architecture..." -ForegroundColor Cyan
# This calls the functions we added to Sentinel-Core
Write-SentinelDocusaurusConfig -SitePath $TargetWebsitePath -Locations $WebLocations
Write-SentinelSidebars -SitePath $TargetWebsitePath -Locations $WebLocations

# --- PHASE 2: PROCESSING LOCATIONS ---
foreach ($loc in $WebLocations) {
    Write-Host "`nProcessing: $($loc.Name) [$($loc.RootType)]" -ForegroundColor Magenta

    # 1. Determine Output Directory
    # If WebSubFolder is 'docs', it goes to the root docs.
    # Otherwise, it goes to an adjacent folder for the plugin.
    $PluginRootPath = Join-Path $TargetWebsitePath $loc.WebSubFolder
    if (!(Test-Path $PluginRootPath)) { New-Item $PluginRootPath -ItemType Directory -Force }

    # 2. Get Source Files (Respecting Grouping)
    $AllFiles = Get-ChildItem $loc.Path -Recurse -File
    $Groups = $AllFiles | Group-Object {
        if ($_.BaseName -match "(.*)$([regex]::Escape($loc.GroupSeparator))") {
            $Matches[1]
        } else {
            $_.BaseName
        }
    }

    # 3. Build Pages
    foreach ($group in $Groups) {
        # Determine relative path to maintain folder structure
        $RelativePath = Resolve-Path $group.Group[0].DirectoryName -Relative -SourcePath $loc.Path
        $TargetDir = Join-Path $PluginRootPath $RelativePath
        if (!(Test-Path $TargetDir)) { New-Item $TargetDir -ItemType Directory -Force }

        Build-WebPageFromTemplate `
            -SourceFiles $group.Group `
            -TargetFolder $TargetDir `
            -AssetExts $ExtList `
            -Overwrite $loc.Overwrite `
            -FolderName $loc.Name `
            -RootType $loc.RootType  # <--- DYNAMICALLY DRIVEN BY CONFIG
    }
}

# --- PHASE 4: GLOBAL ASSETS ---
if (Test-Path $TemplateDir) {
    Copy-Item "$TemplateDir\custom.css" (Join-Path $TargetWebsitePath "src/css/custom.css") -Force -ErrorAction SilentlyContinue
    Get-ChildItem $TemplateDir -Include *.ico, *.svg, *.png | Copy-Item -Destination (Join-Path $TargetWebsitePath "static/img") -Force
}

# --- PHASE 5: LAUNCH ---
Write-Host "PHASE 5: Launching Server..." -ForegroundColor Cyan
Start-SentinelWebsite -Path $TargetWebsitePath -Locations $WebLocations

$globalStopwatch.Stop()
Write-Host "---------------------------------------" -ForegroundColor White
Write-Host " OK: Adjacent Sync Complete ($($globalStopwatch.Elapsed.ToString('mm\:ss')))." -ForegroundColor Cyan