import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import clsx from 'clsx';
// This reads the registry generated by Sentinel Web Gen Phase 1
import navItems from './nav-registry.json';

function NavCard({title, description, link}) {
  return (
    <div className="col col--4 margin-bottom--lg">
      <div className="card shadow--md">
        <div className="card__header">
          <h3>{title}</h3>
        </div>
        <div className="card__body">
          <p>{description}</p>
        </div>
        <div className="card__footer">
          <Link className="button button--primary button--block" to={link}>
            View Archive
          </Link>
        </div>
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <Layout title="Source Studio" description="Sentinel Unified Media Archive">
      <header className="hero hero--primary" style={{padding: '4rem 0', textAlign: 'center'}}>
        <div className="container">
          <h1 className="hero__title">Source Studio</h1>
          <p className="hero__subtitle">Unified Media & Documentation Registry</p>
        </div>
      </header>
      <main>
        <div className="container margin-top--xl">
          <div className="row">
            {navItems.map((props, idx) => (
              <NavCard key={idx} {...props} />
            ))}
          </div>
        </div>
      </main>
    </Layout>
  );
}