import React, { useState } from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import clsx from 'clsx';
// Reads the registry generated by Sentinel Web Gen Phase 1
import navItems from './nav-registry.json';

function NavCard({ title, description, link }) {
  return (
    <div className="col col--4 margin-bottom--lg">
      <div className="card shadow--md">
        <div className="card__header">
          <h3>{title}</h3>
        </div>
        <div className="card__body">
          <p>{description}</p>
        </div>
        <div className="card__footer">
          <Link className="button button--primary button--block" to={link}>
            View Archive
          </Link>
        </div>
      </div>
    </div>
  );
}

export default function Home() {
  const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(false);

  const triggerAction = async (endpoint, actionName) => {
    setLoading(true);
    setStatus(`Executing ${actionName}...`);
    try {
      const response = await fetch(endpoint, { method: 'POST' });
      const data = await response.json();
      if (response.ok && data.status === 'Success') {
        setStatus(`${actionName} completed successfully!`);
      } else {
        setStatus(`Failed to run ${actionName}: ${data.message || 'Unknown error'}`);
      }
    } catch (err) {
      setStatus(`Error executing ${actionName}: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout title="Source Studio" description="Sentinel Unified Media Archive">
      <header className="hero hero--primary" style={{ padding: '4rem 0', textAlign: 'center' }}>
        <div className="container">
          <h1 className="hero__title">Source Studio</h1>
          <p className="hero__subtitle">Unified Media & Documentation Registry</p>
        </div>
      </header>
      <main>
        <div className="container margin-top--xl">
          <div className="card shadow--md margin-bottom--xl" style={{ padding: '1.5rem', borderRadius: '8px' }}>
            <h2>Sentinel Operations Control</h2>
            <p>Trigger automated syncs or perform a complete rebuild of the website scaffolding.</p>
            <div className="button-group">
              <button
                className="button button--primary margin-right--sm"
                disabled={loading}
                onClick={() => triggerAction('/api/sync', 'Media Sync')}
              >
                ▶ Run Sync
              </button>
              <button
                className="button button--warning"
                disabled={loading}
                onClick={() => triggerAction('/api/rebuild', 'Website Rebuild')}
              >
                🛠 Rebuild Website
              </button>
            </div>
            {status && (
              <div className="alert alert--info margin-top--md" role="alert">
                {status}
              </div>
            )}
          </div>

          <div className="row">
            {navItems.map((props, idx) => (
              <NavCard key={idx} {...props} />
            ))}
          </div>
        </div>
      </main>
    </Layout>
  );
}