module.exports = {
  'defaultSidebar': [{'type': 'autogenerated', 'dirName': '.'}],
  'docs': [{'type': 'autogenerated', 'dirName': '.'}],
  'culinary-cuisine': [{'type': 'autogenerated', 'dirName': '.'}],
  'jems-tones': [{'type': 'autogenerated', 'dirName': '.'}],
  'millermade-handcrafted': [{'type': 'autogenerated', 'dirName': '.'}],
};
