// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Jems Tones',
      link: {
        type: 'doc',
        id: 'jems-tones/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'jems-tones',
        },
      ],
    },
    {
      type: 'category',
      label: 'Culinary Cuisine',
      link: {
        type: 'doc',
        id: 'culinary-cuisine/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'culinary-cuisine',
        },
      ],
    },
    {
      type: 'category',
      label: 'MillerMade Handcrafted',
      items: [
        {
          type: 'autogenerated',
          dirName: 'millermade-handcrafted',
        },
      ],
    },
  ],
};

module.exports = sidebars;